### ISSUE TITLE
There seems to be no option in settings to change the hotkey?

### ISSUE THREAD

**Issue by hparlak** [brainstormtrooper/quicktext#16]
There seems to be no option in settings to change the hotkey?

**Comment by brainstormtrooper** [comment]
For now it has to be set through dconf, it's not in the config ui yet...

**Comment by hparlak** [comment]
in dconf there are only keys for file path and the multiline toggle. Please help a bit more.

**Comment by brainstormtrooper** [comment]
Ok, there should be a quick-hotkey setting in dconf. It's a CDATA XML string.

**Comment by brainstormtrooper** [comment]
setting hotkey in prefs ui will be in next release

**Comment by brainstormtrooper** [comment]
12
